  
version: '2'

services:
  web:
    build: .
    command: python app.py
    ports:
     - "80:5000"
    volumes:
     - .:/code

  web2:
    build: ./WS/
    command: python ./WS/app.py
    ports:
     - "5123:5000"
    depends_on:
      - web
    volumes:
     - .:/code